
export const FETCH_POSTS_REQUEST = 'FETCH_POSTS_REQUEST';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_FAIL = 'FETCH_POSTS_FAIL';

export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAIL = 'SIGN_IN_FAIL';

export const SIGN_OUT_REQUEST = 'SIGN_OUT_REQUEST';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
export const SIGN_OUT_FAIL = 'SIGN_OUT_FAIL';

export const SOCIAL_ACCOUNTS_UPDATE_SUCCESS = 'SOCIAL_ACCOUNTS_UPDATE_SUCCESS';
export const SOCIAL_ACCOUNTS_UPDATE_FAIL = 'SOCIAL_ACCOUNTS_UPDATE_FAIL';

export const SERVICE_FACEBOOK_LOAD_SUCCESS = 'SERVICE_FACEBOOK_LOAD_SUCCESS';
export const SERVICE_FACEBOOK_LOAD_FAIL = 'SERVICE_FACEBOOK_LOAD_FAIL';

export const SERVICE_TWITTER_LOAD_SUCCESS = 'SERVICE_TWITTER_LOAD_SUCCESS';
export const SERVICE_TWITTER_LOAD_FAIL = 'SERVICE_TWITTER_LOAD_FAIL';